force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationStatefulBatch.cls
global class JobApplicationStatefulBatch
implements Database.Batchable<SObject>, Database.Stateful {

    global Integer totalProcessed = 0;

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Status__c FROM Job_Application__c WHERE Status__c = \'Applied\''
        );
    }

    global void execute(
        Database.BatchableContext bc,
        List<Job_Application__c> scope
    ) {
        for (Job_Application__c app : scope) {
            app.Status__c = 'Interviewing';
            totalProcessed++;
        }
        update scope;
    }

    global void finish(Database.BatchableContext bc) {
        System.debug('Total records processed: ' + totalProcessed);
    }
}